/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "PRes_aliases.h"
#include "PRes.h"
#include "inTemp_aliases.h"
#include "inTemp.h"
#include "outTemp_aliases.h"
#include "outTemp.h"
#include "AMUX.h"
#include "SARADC.h"
#include "SERVOPWM.h"
#include "SERVO_aliases.h"
#include "SERVO.h"
#include "Clock_1.h"
#include "UVLight_aliases.h"
#include "UVLight.h"
#include "Fan_aliases.h"
#include "Fan.h"
#include "HeatPad_aliases.h"
#include "HeatPad.h"
#include "UART.h"
#include "ISR_UART.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "SARADC_IRQ.h"
#include "SARADC_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

